# 복습문제

In [6]:
class Sports:
    def __init__(self, name, players):
        self.name = name
        self.players = players
    
soccer = Sports('장유선', '축구')
soccer.name

'장유선'

In [8]:
class Sports:
    def __init__(self, name, players):
        self.name = name
        self.players = players
        
    def explain(self):
        print(f"{self.name}는 한 팀당 {self.players}이 하는 스포츠입니다.")
        
soccer = Sports('축구', 11)
soccer.explain()

축구는 한 팀당 11이 하는 스포츠입니다.


In [14]:
class Plant:
    def __init__(self, name):
        self.name = name
        
    def color(self):
        self.color = 'green'
        return self.color
        
소나무 = Plant("소나무")
소나무.color()

'green'

In [17]:
class Apple(Plant):
    def color(self):
        self.color = "Red"
        return self.color

사과 = Apple('사과')
사과.color()

'Red'

In [1]:
with open("new.txt", "w") as f:
    for i in range(10):
        f.write("Hello \n")

In [2]:
with open("new.txt", "r") as f:
    data = f.read()
print(data)

Hello 
Hello 
Hello 
Hello 
Hello 
Hello 
Hello 
Hello 
Hello 
Hello 



In [3]:
with open("gugu.txt", "w") as f:
    for i in range(2,9):
        j = 0
        while j < 9:
            j += 1
            a = i*j
            f.write(f"{a} ")
        f.write("\n")   

In [4]:
with open("gugu.txt", "r") as f:
    data = f.read()
    print(data)

2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 



# 수업

## 클래스 변수

In [35]:
name = "장길산" ### 전역 변수

class Family:
    lastname = "박"  ### 클래스 변수, 클래스 변수는 인스턴스들이 공유한다.
    
    def __init__(self, name):
        self.name = name  ### 인스턴스 변수, 지역 변수
        
    def show_name(self):
        print(name)
        print(Family.lastname)
        print(self.lastname)
        print(self.name)

In [18]:
가족1 = Family("길동")

In [19]:
가족1.name

'길동'

In [20]:
가족1.lastname

'박'

In [21]:
Family.lastname

'박'

In [22]:
가족2 = Family("우치")

In [23]:
가족2.name

'우치'

In [24]:
id(가족1.lastname)

2368140481184

In [25]:
id(가족2.lastname)

2368140481184

In [33]:
f1 = Family('길동')
f1.show_name()

장길산
박
박
길동


In [3]:
## 클래스 이름은 Person
## 전역변수 name에 아이유
## 클래스 변수는 손
## 인스턴스 변수는 입력받아서 흥민
## 3가지 변수 나타내시오

name = "아이유"

class Person:
    c_name = "손"
    
    def __init__(self, i_name):
        self.i_name = i_name
        
    def show_name(self):
        print(name) 
    
    def show_c_name(self):
        print(Person.c_name)
    
    def show_i_name(self):
        print(self.i_name)


class_name = Person("흥민")
class_name.show_name()
class_name.show_c_name()
class_name.show_i_name()

아이유
손
흥민


## 상속 후 변수 추가

In [21]:
class Person:
    def __init__(self):
        self.name = "Lee"
        self.age = 25
        
class Korean(Person):
    pass

In [10]:
p1 = Person()
p1.name

'Lee'

In [11]:
k1 = Korean()
k1.name

'Lee'

In [12]:
print(id(p1.name))
print(id(k1.name))

2286932113136
2286932113136


In [25]:
class Korean(Person):
    def __init__(self):
        self.lang = "한국어"

In [13]:
k1 = Korean
k1.name

AttributeError: type object 'Korean' has no attribute 'name'

In [22]:
class Korean(Person):
    def __init__(self):
        super().__init__()  ###부모 클래스의 init 실행
        self.lang = "한국어"

In [23]:
k2 = Korean()
k2.name

'Lee'

In [30]:
### American class만들고 language는 English
class American(Person):
    def __init__(self):
        super().__init__()
        self.lang = "English"
        
a1 = American()
a1.lang 

'English'

- 부모 클래스에서 인자로 입력받는 것이 있을 때
- 자식 클래스에서도 부모 클래스 인자를 입력해줘야 함

In [57]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
class Korean(Person):
    ### def __init__(self):
    def __init__(self, name, age):
        super().__init__(name, age)
        self.lang = "한국어"

In [58]:
k1 = Korean("홍길동", 22)

In [59]:
k1.lang

'한국어'

In [60]:
k1.name

'홍길동'

- 자식 클래스에서도 인자를 입력받는 경우

In [34]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

class Korean(Person):
    def __init__(self, lang, name, age):  ### 모든 변수를 다 써준다.
        super().__init__(name, age)
        self.lang = "한국어"

In [37]:
k1 = Korean("한국어", "홍길동", 22)

In [38]:
k1.lang

'한국어'

## 모듈
- 함수나 변수 또는 클래스를 모아 놓은 파일임
- .py로 끝남
- 교재 참조(207p)

## 패키지

- double underscore --> dunder

In [39]:
import os
os.getcwd()

'C:\\Users\\admin'

In [40]:
os.mkdir("abc")

In [41]:
os.mkdir("abc/a")

In [42]:
os.mkdir("abc/b")

In [43]:
os.mkdir("abc/c")

In [4]:
import sys
sys.path.append("C:\\Users\\admin\\abc\\a")

In [5]:
sys.path

['C:\\Users\\admin',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310',
 '',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\Pythonwin',
 'C:/Users/admin/abc/a',
 'C:\\Users\\admin\\abc\\a']

## 예외 처리
- except, exception

In [7]:
a = ["Hello", "Good"]

for i in range(3):
    print(a[i])

Hello
Good


IndexError: list index out of range

In [8]:
a = ["Hello", "Good"]
try:
    for i in range(3):
        print(a[i])
except:
    print("에러입니다.")

Hello
Good
에러입니다.


In [9]:
print(4/2)
print(4/0)

2.0


ZeroDivisionError: division by zero

In [11]:
try:
    print(4/2)
    print(4/0)
except ZeroDivisionError as e:
    print(e)
    print("에러입니다")

2.0
division by zero
에러입니다


### 예외 처리 연습

In [ ]:
a = ["Hello", "Good"]

for i in range(3):
    print(a[i])

- 일반적인 에러 처리

In [15]:
a = ["Hello", "Good"]

try:
    for i in range(3):
        print(a[i])
        
except:
    print("Index Error")

Hello
Good
Index Error


- 에러의 종류에 맞는 에러처리


In [16]:
a = ["Hello", "Good"]

try:
    for i in range(3):
        print(a[i])
        
except IndexError as e:
        print(e)

Hello
Good
list index out of range


## 내장 함수

In [17]:
a = "Hello"

In [19]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [20]:
len(a)

5

In [22]:
a = ["a", "b", "c"]

for i in a:
    print(i)

a
b
c


In [24]:
### index도 같이 나타내고싶을 때
for i, j in enumerate(a):
    print(i, j)

0 a
1 b
2 c


In [25]:
d = {"a": 0, "b":1, "c": 2}

In [26]:
d

{'a': 0, 'b': 1, 'c': 2}

In [28]:
### a = ["a", "b", "c"]일 때
### 위의 d와 같은 딕셔너리 c를 만들어라(enumerate 사용)

c = {}
for i, j in enumerate(a):
    c[j] = i
print(c) 

{'a': 0, 'b': 1, 'c': 2}


In [35]:
def positive(a):
    return a > 0

positive(-2)

In [37]:
a = [1, -3, 2, 0, -5, 6]
list(filter(positive, a))

[1, 2, 6]

### Filter
- filter(함수이름, 자료)
- 들어가는 함수는 참.거짓을 return 값으로 가짐
- 자료 안의 원소 하나하나에 대하여 함수를 적용시켜주는 함수 = map

### lambda 함수 사용(자주 사용됨)

In [39]:
a = [1, -3, 2, 0, -5, 6]
list(filter(lambda a: a>0, a))

[1, 2, 6]

## Numpy 사용(filter 기능)

In [40]:
import numpy as np

a = [1, -3, 2, 0, -5, 6]
a = np.array([1, -3, 2, 0, -5, 6])
a

array([ 1, -3,  2,  0, -5,  6])

In [41]:
a > 0

array([ True, False,  True, False, False,  True])

In [42]:
a[a > 0]

array([1, 2, 6])