# 연습문제

In [5]:
a = int(input())

import math
math.factorial(a)


 4


24

In [6]:
a = int(input())

if a % 2 == 0:
    print("짝")
else :
    print("홀")

 3


홀


In [10]:
a = "blueberry smoothie" 

a.count("e")
a.split(" ")

['blueberry', 'smoothie']

In [12]:
import numpy as np
np.linspace(1, 1000, 4)

array([   1.,  334.,  667., 1000.])

In [71]:
import math as m
x = np.linspace[0,2*m.pi,100]
y = np.sin(x)
z = np.cos(x)

plt.plot(x, y)
plt.plot(x, y)

TypeError: 'function' object is not subscriptable

In [39]:
a = '   LIFE-IS-SHORT,-WE-NEED-PYTHON   ' 

b = a.strip().lower().split('-')
" ".join(b).capitalize().replace("p", "P")

'Life is short, we need Python'

In [36]:
from math import factorial, sqrt

In [37]:
factorial(4)

24

In [38]:
sqrt(4)

2.0

In [42]:
a = 1000 % 167
b = 1000 // 167

a + b

170

In [56]:
a = np.linspace(0, 200, 21)
b = a[a <= 80]
b

if a.all() <= 80 :
    b = a

b

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140., 150., 160., 170., 180., 190., 200.])

In [57]:
a=["철수","영희","민수","아영"]

"$".join(a)

'철수$영희$민수$아영'

In [66]:
round(1.4567, ndigits = 2)

1.46

In [70]:
a = 'WezarezstudyingzPython'

a.replace("z"," ")
a.split("z")

['We', 'are', 'studying', 'Python']

In [80]:
a = [4, 3, 8, 6, 9]
b = np.array([4, 3, 8, 6, 9])
b[b < 8]

####list는 비교안됨 np.array()로 바꿔줘야 함

array([4, 3, 6])

In [91]:
a = "gOod$moRning"
b = a.split("$")
b = " ".join(b).lower().capitalize()
b

'Good morning'

# 수업

In [93]:
### 입력받은 것의 두 배 출력해보기
a = input()
b = int(a)*2
print(b)


a = int(input())
print(a*2)

 3


6


In [98]:
### ' '로 여러 개를 입력받기
words = input().split(' ')
words

 a b c 


['a', 'b', 'c', '']

In [99]:
### ','로 여러 개를 입력받기
words = input().split(',')
words

 a, b, c


['a', ' b', ' c']

## formatting

In [101]:
print("I ate three apples. So I have sicked for 3 days")

I ate three apples. So I have sicked for 3 days


- 방법 1

In [112]:
num = 'three'
day = 3

print("I ate num apples. So I have sicked for day days")
print("I ate " + num + " apples. So I have sicked for " + str(day) + " days")


print("I ate {} apples. So I have sicked for {} days".format(num, day))
print("I ate {0} apples. So I have sicked for {1} days".format(num, day))
print("I ate {1} apples. So I have sicked for {0} days".format(num, day))
print("I ate {0} apples. So I have sicked for {0} days".format(num, day))

I ate num apples. So I have sicked for day days
I ate three apples. So I have sicked for 3 days
I ate three apples. So I have sicked for 3 days
I ate three apples. So I have sicked for 3 days
I ate 3 apples. So I have sicked for three days
I ate three apples. So I have sicked for three days


- 방법 2(f string)

In [113]:
num = 'three'
day = 3

print(f"I ate {num} apples. So I have sicked for {day} days")


I ate three apples. So I have sicked for 3 days


In [115]:
### 이름과 나이를 입력받아서 "나의 이름은 000이고 나이는 00세입니다."
name = input("이름")
age = input("나이")

print(f"나의 이름은 {name}이고 나이는 {age}입니다.")

이름 장유선
나이 25


나의 이름은 장유선이고 나이는 25입니다.


## python의 자료형

- 리스트, 튜플, 딕셔너리, 집합
- 리스트는 여러 개를 하나로 묶어주는 역할을 함

### 리스트

- 만들기 : []
- 접근(읽기)
- 수정

#### 만들기

In [129]:
a = [1, 2, 3, 4]
a = [1, 2, 3, 4, "Hello", "Good Morning"] ###list안에 숫자와 문자 모두 가능함
a = [1, 2, 3, 4, "Hello", "Good Morning", [5, 6, 7, 8]] ###list 안에 list도 가능(nested list/중첩리스트)

a

[1, 2, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

In [124]:
type(a)

list

#### 접근

In [127]:
a

[1, 2, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

- 인덱스으로 접근(indexing)

In [128]:
a[0]

1

In [130]:
a[4]

'Hello'

In [131]:
a[6]

[5, 6, 7, 8]

In [132]:
a[6][0]

5

In [133]:
a[5][5]

'M'

In [134]:
a[6][2]

7

In [136]:
a[-1] ###뒤부터 셀 때에는 -1부터 시작

[5, 6, 7, 8]

In [137]:
a[-2][-1]

'g'

In [139]:
a[-0] ### -0은 0으로 인식함

1

- 슬라이싱(slicing)

In [144]:
a[0:4] 
### a[start:stop]
### stop은 포함 안됨

[1, 2, 3, 4]

In [145]:
a[4:6]

['Hello', 'Good Morning']

In [146]:
a[4: ]

['Hello', 'Good Morning', [5, 6, 7, 8]]

In [147]:
a[ :4]

[1, 2, 3, 4]

In [148]:
a[ : ]

[1, 2, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

In [149]:
a[:]

[1, 2, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

In [152]:
a[4][2:4]
### stop - start = 추출하려는 개수 (stop은 포함이 아니기 때문에 가능)

'll'

In [154]:
a[5][5:]

'Morning'

#### 수정

In [155]:
a

[1, 2, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

In [156]:
a[1] = 22

In [157]:
a

[1, 22, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

- 추가

In [158]:
a

[1, 22, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8]]

In [159]:
a.append(9) #### 마지막에 추가됨

In [160]:
a

[1, 22, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8], 9]

In [161]:
a.append("Hi")

In [162]:
a

[1, 22, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8], 9, 'Hi']

In [163]:
b = []
for i in [1, 2, 3]:
    b.append(i)

In [164]:
b

[1, 2, 3]

In [165]:
a.insert(2, 33) ### insert(index, data)

In [167]:
a

[1, 22, 33, 3, 4, 'Hello', 'Good Morning', [5, 6, 7, 8], 9, 'Hi']

- 삭제

In [168]:
a.remove(3)

In [169]:
a

[1, 22, 33, 4, 'Hello', 'Good Morning', [5, 6, 7, 8], 9, 'Hi']

In [170]:
a.pop(4) ### 화면에 무엇을 지웠는지 띄워주고 해당 내용 삭제함

'Hello'

- 정렬
- sorted() : 파이썬 내장함수
- sort() : 메소드

In [172]:
a = [1, 3, 4, 2]

In [173]:
sorted(a)

[1, 2, 3, 4]

In [182]:
a = [3, 4, 1, 5]
a.sort()
a

[1, 3, 4, 5]

In [178]:
a.sorted() ### 둘의 차이 알아두기

AttributeError: 'list' object has no attribute 'sorted'

In [181]:
a.reverse()
a

[1, 3, 4, 5]

### 튜플

- list와 같지만 튜플은 수정을 할 수 없다는 점이 차이점임
- 실수로라도 수정되면 안되는 정보가 있을 때 사용됨

#### 만들기

In [185]:
a = (1, 2, 3, 4)
a

(1, 2, 3, 4)

In [186]:
type(a)

tuple

In [187]:
a = 5, 6, 7, 8

In [188]:
type(a)

tuple

In [189]:
a[0] = 55

TypeError: 'tuple' object does not support item assignment

In [190]:
num = (10, 12)
num

(10, 12)

In [192]:
a, b = num  
### unpacking : 묶여져있는 것을 a,b로 쪼갬
### ()없이 a, b를 입력해도 저절로 () 튜플형으로 저장됨

print(a)   
print(b)

10
12


### 딕셔너리(dictionary)

#### 만들기 | {key : value}

In [195]:
a = {"apple" : "사과", "banana" : "바나나", "cherry" : "체리"}

In [194]:
type(a)

dict

In [196]:
a

{'apple': '사과', 'banana': '바나나', 'cherry': '체리'}

#### 접근, 검색

- 인덱스 없음

In [198]:
a['apple']

'사과'

In [199]:
a[0]

KeyError: 0

In [201]:
a['사과'] ### value로를 검색 안됨

KeyError: '사과'

In [202]:
a.keys()

dict_keys(['apple', 'banana', 'cherry'])

In [203]:
a.values()

dict_values(['사과', '바나나', '체리'])

In [204]:
a.items() ### key와 value 모두 표시

dict_items([('apple', '사과'), ('banana', '바나나'), ('cherry', '체리')])

In [205]:
for i in a.items():
    print(i)

('apple', '사과')
('banana', '바나나')
('cherry', '체리')


In [206]:
for i, j in a.items():
    print(i, j)    ### unpacking

apple 사과
banana 바나나
cherry 체리


In [210]:
a = {"apple": ["사과", "능금", "백설공주"], "banana" : "바나나", "cherry" : "체리"}

In [211]:
a

{'apple': ['사과', '능금', '백설공주'], 'banana': '바나나', 'cherry': '체리'}

#### 수정

In [212]:
a = {"apple": ["사과", "능금", "백설공주"], "banana" : "바나나", "cherry" : "체리"}
a['banana'] = '빠나나'

In [213]:
a

{'apple': ['사과', '능금', '백설공주'], 'banana': '빠나나', 'cherry': '체리'}

#### 추가

In [216]:
a['durian'] = '두리안'
a

{'apple': ['사과', '능금', '백설공주'],
 'banana': '빠나나',
 'cherry': '체리',
 'durian': '두리안'}

In [217]:
명단 = {"철수": "합격", "영희": "합격"}

In [220]:
a = input("이름을 입력하세요.")
print(명단[a])
print(f'{명단[a]}입니다.')

이름을 입력하세요. 철수


합격
합격입니다.


- 집합(set)은 거의 쓰이지않으므로 생략

```
int()
float()
str()
bool()

list() []
tuple() ()
dict() { : }
set() {}
```

In [222]:
a = [1, 2, 3]
a

[1, 2, 3]

In [223]:
id(a)

2063294879168

In [228]:
b = a
b

[1, 2, 3]

In [229]:
c = a.copy()
c

[1, 2, 3]

In [232]:
c[2] = 30
c

[1, 2, 30]

In [233]:
a

[1, 2, 3]

In [234]:
b

[1, 2, 3]

In [237]:
b[2] = 300
b

[1, 2, 300]

In [238]:
a

[1, 2, 300]

In [239]:
id(a)

2063294879168

In [240]:
id(b)

2063294879168

In [241]:
a, b = ('python' 'life')
(a, b) = 'python', 'life'

a = b = 'python'

ValueError: too many values to unpack (expected 2)

## 조건문 IF

- if문의 구조 
```
if 참거짓 : 
    참일 때 실행될 문장
```

In [243]:
if 1 > 2 :
    print("Yes")
else : 
    print("No")

No


```
if  참거짓 :
    참일 때 실행될 문장
elif :
    참일 때 실행될 문장
elif : 
    참일 때 실행될 문장
else :
    나머지 모두에서 실행될 문장
```

- elif : else와 if 줄인 것

In [249]:
## 25보다 크면 "여름"
## 15보다 크면 "가을"
## 5보다 크면 "봄"
## 그 이하는 "겨울"

temp = float(input("기온을 입력하세요: "))

if temp>25 : 
    print("여름")
elif temp>15: 
    print("가을")
elif temp>5: 
    print("봄")
else: 
    print("겨울") 

#### elif를 if로 바꿔서 if를 여러번 쓰면
#### 맞는 조건들에 해당하는 값을 표시할 수 있음(값이 하나 이상일 수 있음)
#### elif사용이 더 좋음

기온을 입력하세요:  17


가을


In [250]:
## 홀수인지 짝수인지 판단
number = int(input())

if number % 2 == 0:
    print("짝수")
else :
    print("홀수")

 4


짝수


- A in B

In [254]:
pocket = ['coins', 'bill', 'card']

if 'bill' in pocket:
    print("택시를 타자")
else : 
    print("걸어가자")

택시를 타자


In [256]:
names = ["영희", "전우치", "홍길동", "장길산"]
name = input("이름을 입력해 주세요")

if name in names: 
    print("합격입니다.")
else: 
    print("불합격입니다.")

이름을 입력해 주세요 철수


불합격입니다.


## 반복문 For

- for문의 구조
```
for i in ....:
    반복할 문장
```

In [259]:
for i in [1, 2, 3]:
    print(i)
    print("hello")
    print()

1
hello

2
hello

3
hello



In [261]:
for i in [1, 2, 3]:
    print()
    print("hello")
    print()

### 안에 i가 없어도 에러가 뜨지 않음


hello


hello


hello



In [262]:
for _ in [1, 2, 3]:
    print("hello")

hello
hello
hello


In [265]:
for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [266]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [274]:
for i in range(1, 10):
    print(i)

### range(시작, 끝, 스텝 수)

1
2
3
4
5
6
7
8
9


In [271]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9


In [273]:
for i in range(0, 11, 3):
    print(i)

0
3
6
9


In [275]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [277]:
for i in range(10):
    print(i, end = ", ")
    print()

0, 
1, 
2, 
3, 
4, 
5, 
6, 
7, 
8, 
9, 


In [279]:
## 2부터 10까지 짝수만 출력
for i in range(2, 11, 2):
    print(i)

2
4
6
8
10


In [281]:
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

2
4
6
8
10


In [282]:
names

['영희', '전우치', '홍길동', '장길산']

In [283]:
for name in names:
    print(name)

영희
전우치
홍길동
장길산


In [284]:
for i in range(4):
    print(names[i])

영희
전우치
홍길동
장길산


- 총합 구하기

In [293]:
sum = 0

for i in range(10):
    sum = sum + i  ### i 만큼씩
print(sum)

45


In [295]:
sum = 0

for i in range(10):
    sum += i  ### i 만큼씩 -=, *=, /= 모두 적용 가능
print(sum)

45


In [297]:
###234부터 567까지의 합은?
sum = 0

for i in range(234, 568):
    sum += i
print(sum)

133767


In [299]:
### 두 수를 입력받아서 두 수에서 두 수 사이의 합은?
a = int(input("1st"))
b = int(input("2nd"))

sum = 0
for i in range (a, b+1):
    sum += i
print(sum)

1st 1
2nd 3


6


In [304]:
### 1부터 20까지의 숫자에서 홀수만
a = []
for i in range(1, 21):
    if i % 2 == 1:
        a.append(i)

print(a)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [306]:
### 구구단
for i in range(1, 10):
    print(f"2 X {i} = {2*i}")

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18


In [315]:
for i in range(2, 10):
    print(f"{i}단입니다.")
    for j in range(1, 10):
        print(f"{i} X {j} = {i*j}")
    print()  

2단입니다.
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18

3단입니다.
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27

4단입니다.
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36

5단입니다.
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45

6단입니다.
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54

7단입니다.
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63

8단입니다.
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72

9단입니다.
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81



# jump to python 예제

## Q1

In [317]:
홍길동 = {"국어" : 80, "영어" : 75, "수학" : 55}
홍길동

{'국어': 80, '영어': 75, '수학': 55}

In [368]:
a = 홍길동['국어']
b = 홍길동['영어']
c = 홍길동['수학']
type(a)
mean = (a + b + c)/3
print(mean)

70.0


## Q2

In [333]:
if 13 % 2 == 0:
    print("짝수")
else:
    print("홀수")

홀수


## Q3

In [383]:
Hong_id = '881120-1068234'
year = Hong_id[1:3]
month = Hong_id[3:5]
date = Hong_id[4:6]
idnr = Hong_id[8: ]

print(f"year = {year}")
print(f"month = {month}")
print(f"date = {date}")
print(f"idnr = {idnr}")

yymmdd = Hong_id[0:6]
print(f"yymmdd = {yymmdd}")

pinum = Hong_id[8: ]
print(f"pin number = {pinum}")

year = 81
month = 12
date = 20
idnr = 068234
yymmdd = 881120
pin number = 068234


## Q4

In [347]:
pin = '881120-1068234'
sex = int(pin[-7])

if sex == 1:
    print("male")
else: 
    print("female")

male


## Q5

In [349]:
a = 'a:b:c:d'
a.replace(":", "#")

'a#b#c#d'

In [363]:
a = [1, 3, 5, 4, 2]
b = sorted(a)
b.reverse()
b

sorted(a).reverse()

[5, 4, 3, 2, 1]

In [397]:
a = [1, 3, 5, 4, 2]

print(sorted(a).reverse())

None


In [395]:
a = [1, 3, 5, 4, 2]

a.sort().reverse()
#### 한 번에 .function()을 쓰는 것은 문자열만 가능

AttributeError: 'NoneType' object has no attribute 'reverse'

In [401]:
a = [1, 3, 5, 4, 2]
type(a.sort())
a.reverse()
a

[5, 4, 3, 2, 1]

In [392]:
a = [1, 3, 5, 4, 2]
sorted(a)
a

[1, 3, 5, 4, 2]

## Q7

In [365]:
a = ['Life', 'is', 'too', 'short']
" ".join(a)

'Life is too short'

## Q8

In [388]:
a = (1, 2, 3)
a = a + (4,)
print(a)

(1, 2, 3, 4)


## Q9

In [370]:
a = dict()
a

{}

In [371]:
a['name'] = 'python'

In [372]:
a[250] = 'python'

In [373]:
a[[1]] = 'python'
## [[]]은 리스트임

TypeError: unhashable type: 'list'

In [375]:
a[('a',)] = 'python'

## Q10

In [377]:
a = {'A': 90, 'B': 80, 'C':70}
a.pop('B')

80

## Q11

In [381]:
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
a1 = [set(a)]
a1
type(a1)

list

In [ ]:
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
aSet = set(a)
b = list(aSet)

## Q12

a와 b가 같은 id number에 저장되었기 때문에 같이 바뀜