# 복습문제

In [13]:
## li=[" ","1","12","123","1234","abc","1a"] 를
## A A AA AAA AAAA AAAAA AaAbAcA AAaA 로 바꾸기

import re

li=[" ","1","12","123","1234","abc","1a"] 

p = re.compile("r[0-9]")
for i in li:
    print(re.sub(p, "A", i))

 
1
12
123
1234
abc
1a


In [17]:
import re

li=[" ","1","12","123","1234","abc","1a"] 

p = re.compile("[0-9]?")
for i in li:
    print(re.sub(p, "A", i), end = " ")

A A AA AAA AAAA AAAAA AaAbAcA AAaA 

In [16]:
import re

li=[" ","1","12","123","1234","abc","1a"] 

p = re.compile("[0-9]*")
for i in li:
    print(re.sub(p, "A", i), end = " ")

A A AA AA AA AA AaAbAcA AAaA 

In [32]:
import numpy as np

a = np.arange(1,101).reshape((10,10)) 
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [47]:
a[4::3,3:6:2]

array([[44, 46],
       [74, 76]])

- a[[0,1],[0,1]] --> [0,0], [1,1]로 인덱싱 됨

- 위 array에서 7, 18, 29, 40 처럼 계단식으로 나타나는 숫자들을 찾을 때 유용함

In [87]:
###data = '''
###  <head>
###    <title>hello world</title>
###  </head>
###''' 
###에서 hello world만 

data = '''
  <head>
    <title>hello world</title>
  </head>
''' 

p = re.compile("(?<=>).+(?=<)")
re.search(p, data).group()

'hello world'

In [84]:
p = re.compile("(?<=>).*(?=<)")
p.search(data).group() 

'hello world'

In [90]:
### 1~35로 구성된 6*6 빙고판을 만들고
### 1_ 짝수만 출력

a = np.arange(1, 37).reshape(6, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [95]:
a[0:, 1::2]

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [96]:
### 2_ 홀수만 출력
a[0:, 0::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [102]:
### 1-99개의 값으로 3차원에 3행을 갖는 array

a = np.arange(1, 100).reshape(3,3,-1)
a

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]],

       [[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]],

       [[67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [ ]:
### factorial
def factorial(n):
    multi = 1
    for i in range(1, n + 1):
        multi *= i
    return multi

In [ ]:
def factorial(n):
    if n == 1:
        return 1
    return n*factorial(n-1)

# 수업
# 파이썬 블로그 추천 : Rfriend

In [122]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [123]:
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

- [1, 2]를 아래로 늘려주는 것(열 방향)은 가능하지만 옆으로 늘리는 것은 안됨

In [125]:
np.array([[1], [2]])

array([[1],
       [2]])

In [124]:
a + np.array([[1], [2]])

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

- 해당 array는 옆으로 늘리는 것 가능

## Numpy 내장함수를 이용하여  array 만들기

### arange(start, stop, step, dtype)

### linspace(start, stop, numbers of element)

In [129]:
np.linspace(1, 9, 5)

array([1., 3., 5., 7., 9.])

### ones(shape, [dtype, order])

In [130]:
np.ones((2,3), dtype = 'int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [131]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### sparse matrix(희소행렬)

In [135]:
### - 10X10 대부분 0
### - 3행 3열 부분 1
### - 5행 6열 부분 1

a = np.zeros((10, 10))

In [136]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
a[3, 3] = 1

In [138]:
a[5, 6] = 1

In [139]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [142]:
### 모든 원소가 3인 10X10인 array

a = np.zeros((10, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [144]:
a[0::] = 3

In [145]:
a

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [146]:
np.ones((10, 10))*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

### diagonal

-  대각선에 무엇이 들어갈 지 지정

### Identity

-  대각선에 1만 들어감

### eye

- identity와 비슷하지만 변수가 두 개도 들어갈 수 있음

### 단위행렬

In [149]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [150]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### full

### empty

### _like() 함수로 배열만들기

- zeros_like
- ones_like
- empty_like
- full_like

데이터타입과 형태를 유지하면서 배열을 채움

In [154]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [155]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [156]:
np.empty_like(a)

array([[          0,           0,   344352432],
       [        444,           0, -2147483648]])

In [158]:
np.full_like(a, 1)

array([[1, 1, 1],
       [1, 1, 1]])

### Copy의 3 가지 방법

In [160]:
a = [1, 2, 3, 4]

In [161]:
a

[1, 2, 3, 4]

In [162]:
## 1
b = a
b

[1, 2, 3, 4]

In [164]:
## 2 (list 일 때)
c = a.copy()
c

[1, 2, 3, 4]

In [166]:
## 3
import copy
d = copy.copy(a)
d

[1, 2, 3, 4]

In [168]:
b[0] = 100
b

[100, 2, 3, 4]

In [169]:
a

[100, 2, 3, 4]

In [170]:
c

[1, 2, 3, 4]

In [171]:
d

[1, 2, 3, 4]

In [172]:
print(id(a))
print(id(b))
print(id(c))
print(id(d))

1907458726976
1907458726976
1907457870592
1907457870080


In [173]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [174]:
b = a
b

array([1, 2, 3, 4])

In [175]:
c = a.copy()
c

array([1, 2, 3, 4])

In [176]:
d = copy.copy(a)
d

array([1, 2, 3, 4])

In [179]:
b[0] = 100
b

array([100,   2,   3,   4])

In [178]:
a

array([100,   2,   3,   4])

In [180]:
c

array([1, 2, 3, 4])

In [181]:
d

array([1, 2, 3, 4])

- id를 공유하는 상태를 View라고 함

In [182]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [183]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [184]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 배열

### 배열의 결합

- hstack
- vstack
- stack : 쌓는 것(First In Last Out/선착순의 반대)
- 맨 마지막에 입력된(가장 최근 작업) 것을 복구해야할 때 사용됨

In [188]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [186]:
np.vstack([a * 10, a * 20])

array([[ 0, 10, 20, 30, 40],
       [ 0, 20, 40, 60, 80]])

In [187]:
np.vstack([a * 10, a * 20]).shape

(2, 5)

In [191]:
a = np.arange(0, 100, 10)
b = np.arange(10) * 20
print(a)
print(b)

[ 0 10 20 30 40 50 60 70 80 90]
[  0  20  40  60  80 100 120 140 160 180]


In [197]:
np.vstack((a, b)) ### 리스트나 array 들어갈 수 있음

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]])

In [195]:
np.hstack((a, b))

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90,   0,  20,  40,
        60,  80, 100, 120, 140, 160, 180])

In [196]:
np.hstack((a, b)).shape

(20,)

In [199]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print(a)
print("")
print(b)

[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]


In [204]:
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [205]:
np.hstack((a, b)).shape

(3, 2)

In [207]:
c = np.dstack((a, b))
c 

### 2차원 자료가 더해지면서 3차원이 됨

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [206]:
c.shape

(3, 1, 2)

### 배열의 분리

- hsplit  : 결과물이 수평일 때 ㅁ|ㅁ
- vsplit  : 결과물이 수직일 때 믐

In [210]:
a = np.arange(32).reshape(4, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [211]:
np.hsplit(a, 2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [213]:
np.hsplit(a, 4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [212]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [215]:
np.vsplit(a, 4)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]])]

## Numpy의 shape 변경 함수

- reshape - 함수로도 사용되나 메소드로 더 많이 사용됨
- flatten
- ravel

In [218]:
a.shape

(4, 8)

In [219]:
a.flatten() ### return copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [221]:
a.flatten().shape

(32,)

In [223]:
a.ravel() ### View (복사본이 아니라 그 자체를 바꿈)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

- transpose : 행과 열의 위치를 바꿈(행렬의 곱셈을 가능하게 해줌)

In [227]:
a = np.arange(1,7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [228]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [229]:
np.transpose(a)

array([[1, 3, 5],
       [2, 4, 6]])

In [230]:
np.swapaxes(a, 0, 1)

array([[1, 3, 5],
       [2, 4, 6]])

In [238]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [240]:
d = np.vsplit(c, 2)
d

[array([[1, 2, 3]]), array([[4, 5, 6]])]

## 비교(Comparison)

In [242]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 3, 4, 2])

a == b ## 안에 있는 각각의 성분을 비교해줌

array([ True, False, False, False])

In [243]:
a > 2

array([False, False,  True,  True])

In [244]:
a[a > 2]

array([3, 4])

## 정렬(Sorting)

In [245]:
a = np.array([1, 3, 4, 2])
a

array([1, 3, 4, 2])

In [246]:
np.sort(a)

array([1, 2, 3, 4])

In [247]:
a

array([1, 3, 4, 2])

In [248]:
a.sort()

In [249]:
a

array([1, 2, 3, 4])

In [251]:
### reverse
a[: :-1]

array([4, 3, 2, 1])

In [252]:
### 축을 지정하여 정렬
x = np.array([[2, 1, 6], 
            [0, 7, 4],
            [5, 3, 2]])
x

array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [255]:
np.sort(x, axis = 0) ## 열만 생각하고 각각의 열대로 배열함 / row-wise

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [254]:
np.sort(x, axis = 1) ## 행 / column-wise

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

## 인덱싱

## 슬라이싱

In [273]:
a = np.arange(0, 6)
a + 10

array([10, 11, 12, 13, 14, 15])

In [279]:
a = np.arange(6)
array = a.copy()
for i in range(5):
    i+=1
    array = np.vstack((array, a+10*i))
array 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [280]:
a = np.array([0,1,2,3,4,5])
b = np.array([[0],[10],[20],[30],[40],[50]])
a+b 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [281]:
a = np.arange(100).reshape(10,10)
a = a[0:6:1,0:6:1]
a 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [287]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [289]:
a[0,3:5]

array([3, 4])

In [307]:
a[4:6, 4:6]

array([[44, 45],
       [54, 55]])

In [305]:
a[2::2, 0::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [308]:
a[ :2]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

## 팬시 인덱싱(Fancy Indexing)

- indexing by position
- indexing by boolean
- indexing by condition

In [309]:
### position
indicies = [1, 2, -3]
a[indicies]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [311]:
a = np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [312]:
a[[1, 2, -3]]

array([10, 20, 50])

In [313]:
### boolean
mask = [False, True, True, False, False, True, False, False]
a[mask]

array([10, 20, 50])

In [316]:
mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype = bool)
a[mask]

array([10, 20, 50])

팬시 인덱싱

In [317]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [320]:
[a[0, 1], a[1, 2], a[2, 0], a[2, 3]]

[1, 6, 8, 11]

In [321]:
a[[0, 1, 2, 2], [1, 2, 0, 3]]

## 바로 윗줄과 같은 표현임

array([ 1,  6,  8, 11])

In [323]:
a = np.arange(25).reshape(5, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [324]:
a[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 1,  7, 13, 19])

## Broadcasting

In [327]:
a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [329]:
b = np.ones((5,))
b

array([1., 1., 1., 1., 1.])

In [330]:
a + b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## Universal Functions(ufuncs)

In [334]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [335]:
sum(a)

array([5, 7, 9])

In [336]:
np.sum(a)

21

In [337]:
np.sum(a, axis = 0)

array([5, 7, 9])

In [338]:
np.sum(a, axis = 1)

array([ 6, 15])

In [339]:
np.min(a)

1

In [341]:
np.max(a)

6

In [342]:
np.min(a, axis = 0)

array([1, 2, 3])

In [343]:
np.min(a, axis = 1)

array([1, 4])

In [347]:
np.argmin(a) ### 1행으로 쭉 펼쳐놓고 min이 되는 index(y가 최소일 때의 x)

0

In [346]:
np.argmax(a) ### 1행으로 쭉 펼쳐놓고 max가 되는 index

5

In [349]:
np.mean(a)

3.5

In [350]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [351]:
a**b

array([  1,  32, 729])

In [352]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [353]:
np.max(a)

3

## where(검색할 때 많이 쓰임)

In [355]:
a = np.array([6, 8, 7, 9, 10], dtype = int)
a

array([ 6,  8,  7,  9, 10])

In [359]:
np.where(a > 7) ### return index

(array([1, 3, 4], dtype=int64),)

In [360]:
index = np.where(a > 7)  ### index를 통해 검색 가능
print(index)
a[index]

(array([1, 3, 4], dtype=int64),)


array([ 8,  9, 10])

In [361]:
np.where(a > 7, "pass", "fail")

### R프로그램에서 ifelse(a > 70, "pass", "fail")와 기능과 문법 같음

array(['fail', 'pass', 'fail', 'pass', 'pass'], dtype='<U4')

In [362]:
####

In [364]:
a = np.arange(-15, 15).reshape(5, 6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [368]:
### 각 행별로 최댓값은 각각 얼마입니까
np.max(a, axis = 1)

array([225,  81,   9,  64, 196])

In [369]:
### 각 열별로 평균은 얼마입니까
np.mean(a, axis = 0)

array([81., 76., 73., 72., 73., 76.])

In [371]:
### 10보다 작은 수를 모두 골라라
index = np.where(a < 10)
a[index]

array([9, 4, 1, 0, 1, 4, 9])

In [372]:
### 10보다 작은 것은 모두 0으로, 크거나 같은 것은 1로 바꾸자
np.where(a < 10, 0, 1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])