# 복습문제

```
match : 맨 처음부터
search : 중간도 가능
findall : 리스트로 출력됨
finditer: iterator를 출력
```

- 정규식에서 매치된 문자열의(시작, 끝)에 해당하는 튜플을 돌려주는 match 객체의 메서드는?

```
obj.group()
obj.start()
obj.end()
obj.span()

해당 문제에서는 obj.span()
```

In [5]:
### Life is too short를 정규식 [A-z]+를 이용하여 리스트 ['Life', 'is', 'too', 'short']로 출력

import re

a = "Life is too short"
re.findall("[A-z]+", a)

['Life', 'is', 'too', 'short']

- 정규식 문자 클래스를 괄호안에 넣으시오
```
[^a-zA-Z0-9_]와 동일한 표현식 ()
\W
```

In [11]:
### 정규식을 사용해서 숫자만 추출
data = """이름 : 김철수
전화번호 : 010 - 1234 - 1234
나이 : 30
성별 남"""

p = re.compile("\d+")
re.findall(p, data)

['010', '1234', '1234', '30']

In [13]:
### ['black', 'blue']만 출력되게 정규식 만들기
s = "black, blue and brown"
p = re.compile("\w+[,]\s\w{4}")
re.findall(p, s)

['black, blue']

In [14]:
s = "black, blue and brown"
p = re.compile("bl\w+")
re.findall(p, s)

['black', 'blue']

In [30]:
### [http http ftp]만 나오게 하기
s= 'http://naver.com http://google.com ftp://daum.net' 

p = re.compile("\w+(?=:)")
re.findall(p, s)


### \w대신 .으로 하면 .은 뭐든지이기 때문에 ftp://daum.net의 앞에 있는 모든 것을 출력함

['http', 'http', 'ftp']

In [29]:
### [naver.com google.com daum.net]만 나오게 하기
s= 'http://naver.com http://google.com ftp://daum.net' 

p = re.compile("(?<=//)\w+[.]\w+")
re.findall(p, s)

['naver.com', 'google.com', 'daum.net']

In [31]:
### [naver.com google.com daum.net]만 나오게 하기
s= 'http://naver.com http://google.com ftp://daum.net' 

p = re.compile("(?<=//)\S+")
re.findall(p, s)

['naver.com', 'google.com', 'daum.net']

In [32]:
### 중복되는 단어들을 finditer를 사용하여 찾기
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
'''

p = re.compile(r"(?P<repeat>\w+)\s+(?P=repeat)")

for i in p.finditer(data):
    print(i)

<re.Match object; span=(7, 14), match='그리고 그리고'>
<re.Match object; span=(21, 24), match='또 또'>
<re.Match object; span=(31, 38), match='그런데 그런데'>
<re.Match object; span=(46, 49), match='끝 끝'>


In [36]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
'''

data = re.findall("\w*\S", data)
set(data)

{'그런데', '그리고', '끝', '또', '안녕하세요'}

In [39]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
'''

set(re.findall("\w+", data))

{'그런데', '그리고', '끝', '또', '안녕하세요'}

# 수업

In [40]:
import urllib.request as req

In [54]:
data = req.urlopen("http://daum.net").read().decode("UTF-8")

###  req.urlopen("http://daum.net") : 접속
###  .read() : 글자 불러오기
###  .decode() :  읽은 수 있는 형태로

In [66]:
data

'<!DOCTYPE html><html lang="ko"> <head> <meta charset="utf-8" /> <title>Daum</title> <meta http-equiv="x-ua-compatible" content="IE=edge" /> <meta property="og:url" content="//www.daum.net/" /> <meta property="og:type" content="website" /> <meta property="og:title" content="Daum" /> <meta http-equiv="Pragma" content="no-cache" /> <meta http-equiv="Expires" content="-1" /> <meta name="referrer" content="origin" /> <meta property="og:image" content="https://i1.daumcdn.net/svc/image/U03/common_icon/5587C4E4012FCD0001" /> <meta property="og:description" content="이용자 선택권을 강화한 뉴스, 세상의 모든 정보를 연결하는 검색. Daum에서 나의 관심 콘텐츠를 즐겨보세요." /> <meta name="description" content="이용자 선택권을 강화한 뉴스, 세상의 모든 정보를 연결하는 검색. Daum에서 나의 관심 콘텐츠를 즐겨보세요." /> <meta name="msapplication-task" content="name=Daum;action-uri=//www.daum.net/;icon-uri=/favicon.ico" /> <meta name="msapplication-task" content="name=미디어다음;action-uri=//news.daum.net/;icon-uri=/media_favicon.ico" /> <meta name="msapplication-task" content="name=메일;acti

In [82]:
data = req.urlopen("http://daum.net").read().decode("UTF-8")

p = re.compile("https\S*[.]js")
li = p.findall(data)
for i in li:
    print(i)

### ^와 $ 은 긴 문장을 하나로 생각하기 때문에 전체에서의 시작과 끝으로 찾아서 나오지 않음

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [89]:
data = req.urlopen("http://daum.net").read().decode("UTF-8")

p = re.compile("https[-:./\w]*[.]js")
li = p.findall(data)
for i in li:
    print(i)

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [185]:
data = """<div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="true" class="M_704" style="display: block;"><span class="WoYOw">이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사장님 너무 친절하시고 빵이 진짜 맛있어요.. 미친 맛,,,,🥹가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ …</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식…</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div> """

In [95]:
data

'<div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="true" class="M_704" style="display: block;"><span class="WoYOw">이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...</span><span class="_3_09q"><svg xmlns="\nhttp://www.w3.org/2000/svg\n" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded

In [124]:
p = re.compile("[가-힣].+[가-힣]")
r = p.findall(data)

for i in r:
    print(i)

이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는
내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다
내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다
내용 더보기</span></span></a></div>

In [125]:
p = re.compile("[^가-힣0-9\s.~!?]")
data = p.sub("", data)
data

'      704   이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다.       704   우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   사진을 

In [137]:
p = re.compile("[가-힣][\w\d\s?!,~]*")
r = p.findall(data)

for i in r:
    print(i) 

이른 아침 문을 여는 빵집입니다
아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요
이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다
가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다
참고로 식빵 나오는 시간은 오전11시~12시 입니다
빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다
우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요
그리고 무엇보다 빵이 정말 맛있어요
제주도에서 원탑입니다!!! 여기보다 두배는 
내용 더보기      704   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  
내용 더보기      704   인절미빵
먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다
내용 더보기      704   사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요   여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서
내용 더보기      704   성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주
내용 더보기      704   사장님 너무 친절하시고 빵이 진짜 맛있어요
미친 맛가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요??!?! 저희 동네에 있었음 매일 가고싶네요  309 

내용 더보기      704   재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식 309 

내용 더보기 


In [186]:
p = re.compile("[가-힣][\w\d\s?!,~]*")
s = p.findall(data)

for i in s:
    print(re.sub("\d{3}", "", i))

이른 아침 문을 여는 빵집입니다
아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요
이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다
가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다
참고로, 식빵 나오는 시간은 오전11시~12시 입니다
빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다
우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요
그리고 무엇보다 빵이 정말 맛있어요
제주도에서 원탑입니다!!! 여기보다 두배는 
내용 더보기
맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  
내용 더보기
인절미빵
먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다
내용 더보기
사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서
내용 더보기
성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주
내용 더보기
사장님 너무 친절하시고 빵이 진짜 맛있어요
미친 맛,,,,
가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ 
내용 더보기
재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식
내용 더보기


## 자주 쓰이는 패턴

### 전화번호

In [133]:
### 010-1234-5678
p = re.compile("\d+[-]\d+[-]\d+")

##"\d{2, 3}[-]\d{4}[-]\d{4}"

### 이메일

In [ ]:
### prince@naver.com   hello@daum.net   morning@company.co.kr
p = re.compile("\S+[@]\S+")

### [A-z0-9]+@[A-z0-9]+[.][a-z.]+

### 주민번호

In [138]:
### 210203-21345676
p = re.compile("\d{6}[-][123456]\d{6}")

In [160]:
### ['http:', 'https:', 'ftp:']

text = '''
http://www.google.com/

https://mail.google.com/

ftp://ftp.google.com/

''' 

p = re.compile("\w+[:]")
p.findall(text)

['http:', 'https:', 'ftp:']

In [161]:
### ['http', 'https', 'ftp']

p = re.compile("\w+(?=:)")
p.findall(text)

['http', 'https', 'ftp']

In [162]:
### 숫자만

text = '''apple: $50.24
banana: $35.25
pizza: $100
''' 

p = re.compile("[\d.]+")
p.findall(text)

['50.24', '35.25', '100']

In [171]:
text = '''apple: $50.24
banana: $35.25
pizza: $100
''' 

p = re.compile("(?<=[$]).+")
p.findall(text)



['50.24', '35.25', '100']

In [182]:
text = '''<p>이른 아침 문을 여는 빵집입니다</p>
<h1>아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요</h1>
<h5>이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다</h5>
<p>가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다</p>
<p>참고로 식빵 나오는 시간은 오전시시 입니다</pp>
''' 

p = re.compile("(?<=<p>).+(?=</p>)")
p.findall(text)

['이른 아침 문을 여는 빵집입니다', '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다']

# 연습문제

In [188]:
a = 'a:b:c:d'
b = a.split(':')
"#".join(b)

'a#b#c#d'

In [189]:
a = {"A":90, "B":80}
a["C"] = 70
a["C"]

70

In [190]:
A = [20, 55, 67, 82, 45, 33, 90, 87, 100, 25]

total = 0
for i in A:
    total += i
print(total)

604


In [196]:
li = []



def arrr(n):
    result = 0
    count = 0
    if result == 0:
        li.append(li)
        result += 1
        li.append(li)
        count += 1
    elif 0 and 1 in li:
        while result < n:
            x = li[count] + li[count-1]
            count += 1
            li.append(x)
    return li
        

In [197]:
arrr(10)

[[...], [...]]

In [198]:
def total(*args):
    total = 0
    for i in args:
        total += i
    return total

In [199]:
total(65, 45, 2, 3, 45, 8)

168

In [203]:
a = int(input("구구단을 출력할 숫자를 입력하세요(2~9): "))

for i in range(1, 10):
    print(i*a, end = " ")

구구단을 출력할 숫자를 입력하세요(2~9):  2


2 4 6 8 10 12 14 16 18 

In [245]:
text = """AAA
BBB
CCC
DDD
EEE
"""

with open("abc.txt", "w") as f:
    f.write(text)

In [250]:
with open("abc.txt") as f:
    data = f.readlines()
    
data.reverse()

with open("abc.txt", "w") as f:
    for i in data:
        f.write(i)

In [252]:
sample = """70
60
55
75
95
90
80
80
85
100"""

with open("sample.txt", "w") as f:
    f.write(sample)

In [254]:
os.getcwd()

'C:\\Users\\admin'

In [350]:
class Calculator:
    def __init__(self, li):
        self.li = li
        self.total = 0
        
    def sum(self):
        for i in self.li:
            self.total += i
        return self.total

    def avg(self):
        for i in self.li:
            self.total += i
        return self.total/len(self.li)

call1 = Calculator([1, 2, 3, 4, 5])
call1.sum()
call1.avg()

call2 = Calculator([6, 7, 8, 9, 10])
call2.sum()
call2.avg()

16.0

In [387]:
result = 0
try:
    [1, 2, 3][3]
    'a' + 1
    4 / 0
except TypeError:
    result += 1
except ZeroDivisionError:
    result += 2
except IndexError:
    result += 3
finally:
    result += 4

print(result)

7


In [391]:
data = "454673"

numbers = list(map(int, data))
result = []

for i, num in enumerate(numbers):
    result.append(str(num))
    if i < len(numbers)-1:
        is_odd = num % 2 == 1
        is_next_odd = numbers[i+1] % 2 == 1
        if is_odd and is_next_odd:
            result.append("-")
        elif not is_odd and not is_next_odd:
            result.append("*")

print("".join(result))

454*67-3


In [397]:
def compress_string(s):
    _c = ""
    cnt = 0
    result = ""
    for c in s:
        if c != _c:
            _c = c
            if cnt: 
                result += str(cnt)
            result += c
            cnt = 1
        else:
            cnt += 1
    if cnt: 
        result += str(cnt)
    return result

print(compress_string("aaabbcccccca"))

a3b2c6a1


In [408]:
def chkDupNum(s):
    result = []
    for num in s:
        if num not in result:
            result.append(num)
        else:
            return False
    return len(result) == 10

print(chkDupNum("0123456789"))
print(chkDupNum("01234"))
print(chkDupNum("01234567890"))
print(chkDupNum("6789012345"))
print(chkDupNum("012322456789"))

True
False
False
True
False


In [416]:
dic = {
    '.-':'A','-...':'B','-.-.':'C','-..':'D','.':'E','..-.':'F',
    '--.':'G','....':'H','..':'I','.---':'J','-.-':'K','.-..':'L',
    '--':'M','-.':'N','---':'O','.--.':'P','--.-':'Q','.-.':'R',
    '...':'S','-':'T','..-':'U','...-':'V','.--':'W','-..-':'X',
    '-.--':'Y','--..':'Z'
}


def morse(src):
    result = []
    for word in src.split("  "):
        for char in word.split(" "):
            result.append(dic[char])
        result.append(" ")
    return "".join(result)


print(morse('.... .  ... .-.. . . .--. ...  . .- .-. .-.. -.--'))

HE SLEEPS EARLY 


In [419]:
p = re.compile("[a-z]+")
m = p.search("5 python")
print(m.start())
print(m.end())

2
8


In [436]:
text = """park 010-9999-9988
kim 010-9909-7789
lee 010-8789-7768
"""

pat = re.compile("\d{4}$", re.MULTILINE)
result = re.sub(pat, "####" ,text)

print(result)

park 010-9999-####
kim 010-9909-####
lee 010-8789-####



In [439]:
pat = re.compile(".*[@].*[.](?=com$|net$).*$")

print(pat.match("pahkey@gmail.com"))
print(pat.match("kim@daum.net"))
print(pat.match("lee@myhome.co.kr"))

<re.Match object; span=(0, 16), match='pahkey@gmail.com'>
<re.Match object; span=(0, 12), match='kim@daum.net'>
None


In [421]:
id_list = []
pw_list = []

class Membership:
    def __init__(self, id_, pw_):
        self.id_ = id_
        self.pw_ = pw_
    
    def join(self):
        a = input("type your id: ")
        if a in id_list:
            print("this id is not available.")
        else:
            id_list.append(a)

        b = input("type your pw: ")
        if re.match("[A-z]+[0-9]+", b):
            pw_list.append(b)
        else:
            print("please make pw only with alphabet and number")

In [422]:
b = Membership('deu05077', 'jang@05027')
b.join()
pw_list

type your id:  deu05077
type your pw:  jang@05027


please make pw only with alphabet and number


[]

## Numpy(Numerical Python / Numeric Python)

- 2차원에서는  (행[0], 열[1])이므로 axis 0 = 행, axis 1 = 열
- 3차원에서는 (z[0], y[1], x[2])
- element wise : Numpy의 연산은 원소들끼리 이루어진다

In [255]:
 import numpy as np

### ndarray(n dimensional array)
- 1차원 : (3,)
- 2차원 : (2, 3)

### 행렬 Matrix
- matrix는 2차원만 가능함

### 배열 만들기

In [261]:
a = np.array([0, 1, 2, 3])
print(a)

a

[0 1 2 3]


array([0, 1, 2, 3])

In [263]:
### 구조
a.shape

(4,)

In [264]:
### 사이즈
a.size

4

In [273]:
### 데이터형(숫자는 byte)
a.dtype

dtype('int32')

In [271]:
a = np.array([0, 1, 2, 3, 4.0])
a.dtype

dtype('float64')

In [272]:
a = np.array([0, 1, 2, 3, 4.3], dtype = 'int')
a.dtype

dtype('int32')

In [275]:
a = np.array([0, 1, 2, 3], dtype = 'float')
a

array([0., 1., 2., 3.])

In [279]:
a = np.array([0, 1, 2, 3], dtype = 'float16')
a

array([0., 1., 2., 3.], dtype=float16)

In [280]:
a = np.array([0, 1, 2, 3], dtype = 'int8')
a

array([0, 1, 2, 3], dtype=int8)

In [270]:
### 차원
a.ndim

1

In [ ]:
li = [0, 1, 2, 3]
np.array(li)

### 파이썬과 넘파이 계산속도 비교

In [281]:
list1 = [1, 2, 3, 4]
list2 = [1, 2, 3, 4]
list1 + list2

[1, 2, 3, 4, 1, 2, 3, 4]

In [285]:
list3 = []
for i in range(4):
    a = list1[i] + list2[i]
    list3.append(a)
    
list3

[2, 4, 6, 8]

In [287]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([1, 2, 3, 4])

array3 = array1 + array2
array3

array([2, 4, 6, 8])

In [289]:
def add_list(n):
    li1 = list(range(1, n + 1))
    li2 = list(range(1, n + 1))
    li3 = []
    
    for i in range(n):
        li3.append(li1[i] + li2[i])
    
    return li3

add_list(10)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [290]:
def add_array(n):
    array1 = np.array(range(1, n + 1))
    array2 = np.array(range(1, n + 1))
    array3 = array1 + array2
    
    return array3

add_array(10)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [306]:
li1 = list(range(10000))
li2 = list(range(10000))

def add_list():
    li3 = []
    
    for i in range(10000):
        li3.append(li1[i] + li2[i])
    
    return li3

add_list()

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [307]:
array1 = np.array(range(10000))
array2 = np.array(range(10000))

def add_array():
    array3 = array1 + array2
    
    return array3

add_array()

array([    0,     2,     4, ..., 19994, 19996, 19998])

In [308]:
import timeit

print(timeit.timeit(add_list, number = 100000))
### add_list 함수를 10번 반복시키는 데에 걸린 시간

print(timeit.timeit(add_array, number = 100000))

105.57016479999947
0.7781775000003108


### 2차원 배열 만들기

In [309]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [311]:
np.arange(10)

### 결과물 list가 아닌 array임

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [314]:
np.arange(10).reshape((2, 5))

### reshape안에 괄호를 한 번 더 해서 2행 5열의 2차원임을 의미(안해줘도 되기는 함)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [315]:
np.arange(12).reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [317]:
np.arange(12).reshape((3, -1))

### -1을 적어도 자동으로 뒤에 나올 숫자가 나옴

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [320]:
np.arange(24).reshape(2, 3, 4)

### x = 4, y = 3, z = 2
### 3행 4열이 2장 나옴

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [323]:
np.arange(36).reshape(3, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [327]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print(" ")
print(b)
print(" ")
a + b

[[1 2]
 [3 4]]
 
[[5 6]
 [7 8]]
 


array([[ 6,  8],
       [10, 12]])

In [329]:
a ** b

array([[    1,    64],
       [ 2187, 65536]])

In [333]:
print(a)
print(" ")

c = np.array([5, 6])

print(c)
print(" ")

a + c

## [5, 6]을 복제해서 맞춰서 계산해줌
## broadcasting

[[1 2]
 [3 4]]
 
[5 6]
 


array([[ 6,  8],
       [ 8, 10]])

In [335]:
a + 5

## 정수 5를 array로 만들어서 자동으로 계산해줌

array([[6, 7],
       [8, 9]])

In [336]:
c = np.array([5, 6, 7])
a + c

## 알아서 줄이는 것은 안됨

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [338]:
a = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([5, 6])
a + c

## 늘려도 맞추기 힘든 경우도 안됨

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [340]:
a = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
c = np.array([5, 6])
a + c

## 하나가 한 방향으로만 늘어날 수 있음
## 하나가 양방향으로 늘어나지는 못함

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

### 2D Slicing

In [371]:
a = np.arange(25).reshape((5, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [367]:
a[4]

array([20, 21, 22, 23, 24])

In [372]:
a[:,(1, 4)]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19],
       [21, 24]])

In [386]:
a[(1,3),0:3:2]

array([[ 5,  7],
       [15, 17]])

In [ ]:
a = np.arange(25).reshape((5, 5))
a[4]
a[:,(1, 4)]
a[(1,3),0:3:2]